"""Multi-view diffusion transformer.

Every view (RGB + depth, 4 channels) is concatenated with its per-pixel Plücker ray map
(6 channels), patchified, and all views are put into one token sequence with full
attention. There is no view-index embedding, so the context is an unordered *set* of
posed observations: position comes only from geometry, as in Atlas's spatial context.
Only the target view is noisy; its tokens are decoded into a velocity prediction.
"""
import math

import torch
import torch.nn as nn
import torch.nn.functional as F


def patchify(x, p):
    B, V, C, H, W = x.shape
    x = x.reshape(B, V, C, H // p, p, W // p, p).permute(0, 1, 3, 5, 2, 4, 6)
    return x.reshape(B, V, (H // p) * (W // p), C * p * p)


def unpatchify(x, p, C, H, W):
    B = x.shape[0]
    x = x.reshape(B, H // p, W // p, C, p, p).permute(0, 3, 1, 4, 2, 5)
    return x.reshape(B, C, H, W)


class TimestepEmbedder(nn.Module):
    def __init__(self, dim, freq_dim=256):
        super().__init__()
        self.freq_dim = freq_dim
        self.mlp = nn.Sequential(nn.Linear(freq_dim, dim), nn.SiLU(), nn.Linear(dim, dim))

    def forward(self, t):
        half = self.freq_dim // 2
        freqs = torch.exp(-math.log(10000) * torch.arange(half, device=t.device) / half)
        a = (t.float() * 1000)[:, None] * freqs[None]
        return self.mlp(torch.cat([a.cos(), a.sin()], -1))


class Block(nn.Module):
    def __init__(self, dim, heads, mlp_ratio=4.0):
        super().__init__()
        self.heads = heads
        self.n1 = nn.LayerNorm(dim, elementwise_affine=False, eps=1e-6)
        self.n2 = nn.LayerNorm(dim, elementwise_affine=False, eps=1e-6)
        self.qkv = nn.Linear(dim, 3 * dim)
        self.proj = nn.Linear(dim, dim)
        self.qn = nn.RMSNorm(dim // heads)
        self.kn = nn.RMSNorm(dim // heads)
        hidden = int(dim * mlp_ratio)
        self.mlp = nn.Sequential(nn.Linear(dim, hidden), nn.GELU(approximate="tanh"), nn.Linear(hidden, dim))
        self.ada = nn.Linear(dim, 6 * dim)
        nn.init.zeros_(self.ada.weight)
        nn.init.zeros_(self.ada.bias)

    def forward(self, x, c, mask):
        B, L, D = x.shape
        sh1, sc1, g1, sh2, sc2, g2 = self.ada(F.silu(c))[:, None].chunk(6, -1)
        h = self.n1(x) * (1 + sc1) + sh1
        q, k, v = self.qkv(h).view(B, L, 3, self.heads, D // self.heads).permute(2, 0, 3, 1, 4)
        a = F.scaled_dot_product_attention(self.qn(q), self.kn(k), v, attn_mask=mask)
        x = x + g1 * self.proj(a.transpose(1, 2).reshape(B, L, D))
        return x + g2 * self.mlp(self.n2(x) * (1 + sc2) + sh2)


class MiniAtlas(nn.Module):
    """The target view uses fine patches (detail matters there); context views use coarser
    patches, which keeps the sequence short enough to train on a laptop GPU."""

    def __init__(self, img=64, patch=4, ctx_patch=8, dim=384, depth=12, heads=6, in_ch=4, ray_ch=6,
                 cache_ch=0, cache_factor=1):
        super().__init__()
        self.config = dict(img=img, patch=patch, ctx_patch=ctx_patch, dim=dim, depth=depth, heads=heads,
                           in_ch=in_ch, ray_ch=ray_ch, cache_ch=cache_ch, cache_factor=cache_factor)
        self.img, self.patch, self.ctx_patch, self.in_ch = img, patch, ctx_patch, in_ch
        self.P = (img // patch) ** 2
        self.Pc = (img // ctx_patch) ** 2
        self.embed = nn.Linear((in_ch + ray_ch) * patch * patch, dim)
        self.embed_ctx = nn.Linear((in_ch + ray_ch) * ctx_patch * ctx_patch, dim)
        self.pos = nn.Parameter(torch.randn(1, self.P, dim) * 0.02)
        self.pos_ctx = nn.Parameter(torch.randn(1, 1, self.Pc, dim) * 0.02)
        self.t_emb = TimestepEmbedder(dim)
        self.tau_proj = nn.Linear(dim, dim)                     # context noise-augmentation level
        self.gen_emb = nn.Parameter(torch.zeros(dim))           # context view was generated by the model
        # 3D cache: the reprojected memory, given at image resolution (cache_factor x the token grid)
        self.cache_patch = patch * cache_factor
        if cache_ch:
            self.embed_cache = nn.Linear(cache_ch * self.cache_patch ** 2, dim)
            nn.init.zeros_(self.embed_cache.weight)
            nn.init.zeros_(self.embed_cache.bias)
        nn.init.zeros_(self.tau_proj.weight)
        nn.init.zeros_(self.tau_proj.bias)
        self.blocks = nn.ModuleList([Block(dim, heads) for _ in range(depth)])
        self.final_norm = nn.LayerNorm(dim, elementwise_affine=False, eps=1e-6)
        self.final_ada = nn.Linear(dim, 2 * dim)
        self.out = nn.Linear(dim, patch * patch * in_ch)
        for m in (self.final_ada, self.out):
            nn.init.zeros_(m.weight)
            nn.init.zeros_(m.bias)

    def forward(self, xt, t, tgt_ray, ctx=None, ctx_ray=None, ctx_mask=None, ctx_tau=None, ctx_gen=None,
                cache=None):
        """xt [B,C,H,W] noisy target, t [B], tgt_ray [B,6,H,W];
        ctx [B,K,C,H,W], ctx_ray [B,K,6,H,W], ctx_mask [B,K] bool, ctx_tau [B,K],
        ctx_gen [B,K] bool (view is the model's own output rather than an observation),
        cache [B,5,H*f,W*f] memory reprojected into the target camera (see cache.py)."""
        B, D, P, Pc = xt.shape[0], self.pos.shape[-1], self.P, self.Pc
        x = self.embed(patchify(torch.cat([xt, tgt_ray], 1)[:, None], self.patch))[:, 0] + self.pos
        if cache is not None and hasattr(self, "embed_cache"):
            x = x + self.embed_cache(patchify(cache[:, None].to(x.dtype), self.cache_patch))[:, 0]
        c = self.t_emb(t)
        K = 0 if ctx is None else ctx.shape[1]
        mask = None
        if K:
            tok = self.embed_ctx(patchify(torch.cat([ctx, ctx_ray], 2), self.ctx_patch)) + self.pos_ctx
            tok = tok + self.tau_proj(F.silu(self.t_emb(ctx_tau.flatten()))).view(B, K, 1, D)
            if ctx_gen is not None:
                tok = tok + ctx_gen.to(tok.dtype)[:, :, None, None] * self.gen_emb
            x = torch.cat([x, tok.reshape(B, K * Pc, D)], 1)
            valid = torch.cat([torch.ones(B, P, dtype=torch.bool, device=xt.device),
                               ctx_mask[:, :, None].expand(B, K, Pc).reshape(B, K * Pc)], 1)
            mask = valid[:, None, None]
        for blk in self.blocks:
            x = blk(x, c, mask)
        sh, sc = self.final_ada(F.silu(c))[:, None].chunk(2, -1)
        x = self.out(self.final_norm(x[:, :P]) * (1 + sc) + sh)
        return unpatchify(x, self.patch, self.in_ch, self.img, self.img)
